"""Initial migration.

Revision ID: a6ac96799627
Revises: 
Create Date: 2024-09-18 01:43:39.502311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac96799627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_description', sa.String(length=255), nullable=False))
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('text_description')

    # ### end Alembic commands ###
